import type { Metadata } from 'next'
import Head from 'next/head'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  other: {},
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <Head>
        <meta
          httpEquiv='Cache-Control'
          content='no-cache, no-store, must-revalidate'
        />
        <meta httpEquiv='Pragma' content='no-cache' />
        <meta httpEquiv='Expires' content='0' />
        <meta name='cache-control' content='max-age=0' />
        <meta name='version' content='2.1.20241207' />
        <meta name='last-modified' content='2025-08-07' />
      </Head>
      <body className='max-w-4xl mx-auto p-5 bg-gradient-to-r from-[var(--primarybg)] to-[var(--secondarybg)] min-h-screen'>
        <div className='container mx-auto'>
          <main>{children}</main>
        </div>
      </body>
    </html>
  )
}
